
aws:
  region: us-east-1
  buckets:
    profile-media-bucket-name: test-img-handling

##to avoid 'org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.'
## If we try to upload a large file, a MaxUploadSizeExceededException exception will be thrown.
# However, we can tune the file upload limits through the properties spring.servlet.multipart.max-file-size and
# spring.servlet.multipart.max-request-size that we define in the application.properties file.
spring:
  servlet:
    multipart:
      max-file-size: 50MB

