spring:
  application:
    name: SpringBootSQSSNSSWSDemo

logging:
  level:
    org.springframework.web: TRACE

sqs:
  resume_parser_queue_url: https://sqs.us-east-1.amazonaws.com/900543170460/resume-parser
  resume_parser_dlq_queue_url: https://sqs.us-east-1.amazonaws.com/900543170460/resume-parser-dlq


