spring:
  application:
    name: SpringBootEmailDemoApp
  #mail properries
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com #specifies the SMTP server host. In this case, we’re using Gmail’s SMTP server. Change this value if you’re using a different SMTP server
    port: 587 #specifies the port number used to establish a connection with the SMTP server. For Gmail's SMTP server, the recommended port is 587.
    username: ${E_USERNAME} #the email address of the account you want to use as the sender of the emails
    password: ${E_PASSWORD} #property requires the password or app-specific password associated with the email account specified in the spring.mail.username property. For security reasons, it's crucial not to use the account's actual password. Instead, generate an app-specific password from the email service provider and use it here
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true #this property is used to enable SMTP authentication. When set to true, it indicates that the SMTP server requires authentication before sending emails. This is usually the case for most SMTP servers.
          starttls:
            enable: true #to enable the use of Transport Layer Security (TLS) to encrypt the connection. When set to true, it ensures that the connection is secured using TLS encryption