logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  security:
    debug: true

  datasource:
    #url: jdbc:mysql://localhost:3306/productsdb
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.H2Dialect
  show-sql: true

app:
  jwt:
    secret:
      signKey: test!!!@#!!!4500-~!%&!
      encryptKey: testMe!!!!
    expiryInSeconds: 300 #5 mins
